import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import ThemeConfigProvider from "@/providers/theme.provider";
import APIContextProvider from "@/providers/api.provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kestrel Dashboard",
  description: "Generated by JosephNK",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = {
    // Primary
    colorPrimary: "#8e51bd",

    // 폰트 시스템
    fontFamily: `var(--font-geist-sans)`,
    fontFamilyCode: `var(--font-geist-mono)`,
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
          <ThemeConfigProvider token={token}>
            <APIContextProvider>{children}</APIContextProvider>
          </ThemeConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
