import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { font1, font2, themeToken } from "@/utils/font/font";
import ThemeConfigProvider from "@/providers/theme.provider";
import QueryProviders from "@/utils/react-query/query-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Kestrel Dashboard",
  description: "Generated by JosephNK",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font1.variable} ${font2.variable}`}>
        <QueryProviders>
          <AntdRegistry>
            <ThemeConfigProvider token={themeToken}>
              {children}
            </ThemeConfigProvider>
          </AntdRegistry>
        </QueryProviders>
      </body>
    </html>
  );
}
